version: '3'

services:
  pdf_api:
    container_name: pdf_api
    restart: always
    build: ./pdf_api
    ports:
      - "8000:8000"
    command: gunicorn -w 2 --timeout 90 -b 0.0.0.0:8000 wsgi:app

  nginx_pdf:
    container_name: nginx_pdf
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - pdf_api